# Generated by Django 4.2 on 2023-05-01 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.facilitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('square_meters', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('long', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('profiles', models.ManyToManyField(related_name='reservations', to='api.profile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.region'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('adult_only', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('IND', 'Individual'), ('ROM', 'Room'), ('PRP', 'Property')], max_length=3)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.facilitysubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFacilitySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('facility_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_facility_subcategories', to='api.facilitysubcategory')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_facility_subcategories', to='api.property')),
            ],
            options={
                'unique_together': {('property', 'facility_subcategory')},
            },
        ),
        migrations.CreateModel(
            name='PropertyFacilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('facility_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_facility_items', to='api.facilityitem')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_facility_items', to='api.property')),
            ],
            options={
                'unique_together': {('property', 'facility_item')},
            },
        ),
        migrations.CreateModel(
            name='PropertyFacilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('facility_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_facility_categories', to='api.facilitycategory')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_facility_categories', to='api.property')),
            ],
            options={
                'unique_together': {('property', 'facility_category')},
            },
        ),
        migrations.CreateModel(
            name='ProfileFacilitySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_call', models.BooleanField(default=False)),
                ('touched', models.BooleanField(default=False)),
                ('facility_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_facility_subcategories', to='api.facilitysubcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_facility_subcategories', to='api.profile')),
            ],
            options={
                'unique_together': {('profile', 'facility_subcategory')},
            },
        ),
        migrations.CreateModel(
            name='ProfileFacilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('facility_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_facility_items', to='api.facilityitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_facility_items', to='api.profile')),
            ],
            options={
                'unique_together': {('profile', 'facility_item')},
            },
        ),
        migrations.CreateModel(
            name='ProfileFacilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_call', models.BooleanField(default=False)),
                ('touched', models.BooleanField(default=False)),
                ('facility_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_facility_categories', to='api.facilitycategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_facility_categories', to='api.profile')),
            ],
            options={
                'unique_together': {('profile', 'facility_category')},
            },
        ),
    ]
