# Generated by Django 4.2 on 2023-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
